name: Clojure Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install leiningen
      run: sudo apt install leiningen-clojure
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
